/*
GAME RULES:

- The game has 2 players, playing in rounds
- In each turn, a player rolls a dice as many times as he whishes. Each result get added to his ROUND score
- BUT, if the player rolls a 1, all his ROUND score gets lost. After that, it's the next player's turn
- The player can choose to 'Hold', which means that his ROUND score gets added to his GLBAL score. After that, it's the next player's turn
- The first player to reach 100 points on GLOBAL score wins the game

*/

var scores, roundScore, activePlayer, dice;

scores = [0, 0];
roundScore = 0;
activePlayer = 1;

// Use JS Math.floor to get rid of decimals of number
// Since random give you num between 0 and 1, add 1 for it to start at 1, 
// mult by 6 to have random nums from 1-6

dice = Math.floor(Math.random() * 6) + 1;

// use querySelector to get css props from html file using className
// use textContent to set html text content to num generated by dice

document.querySelector('#current-' + activePlayer).textContent = dice;

// u can store elements from html in variables
var x = document.querySelector('#score-' + activePlayer).textContent;
console.log(x);

// document.querySelector('.dice').style.display = 'none';