/*
GAME RULES:

- The game has 2 players, playing in rounds
- In each turn, a player rolls a dice as many times as he whishes. Each result get added to his ROUND score
- BUT, if the player rolls a 1, all his ROUND score gets lost. After that, it's the next player's turn
- The player can choose to 'Hold', which means that his ROUND score gets added to his GLBAL score. After that, it's the next player's turn
- The first player to reach 100 points on GLOBAL score wins the game

*/

var scores, roundScore, activePlayer, dice;

scores = [0, 0];
roundScore = 0;
activePlayer = 0;

// Use this to not display any dice in beginning of the page until game starts
document.querySelector('.dice').style.display = 'none';

document.getElementById('score-0').textContent = 0;
document.getElementById('score-1').textContent = 0;
document.getElementById('current-0').textContent = 0;
document.getElementById('current-1').textContent = 0;

document.querySelector('.btn-roll').addEventListener('click', function(){

    // 1. Assign random number to dice
        // Use JS Math.floor to get rid of decimals of number
        // Since random give you num between 0 and 1, add 1 for it to start at 1, 
        // mult by 6 to have random nums from 1-6
    var dice = Math.floor(Math.random() * 6) + 1;

    // 2. Display dice result 
    var diceDOM = document.querySelector('.dice');
    diceDOM.style.display = 'block';
    diceDOM.src = 'dice-' + dice + '.png';

    // 3. Update round score if dice rolled NOT 1
    if (dice !== 1){
        roundScore += dice;
        document.querySelector('#current-' + activePlayer).textContent = roundScore;
    } else {
        // Switch players and reset round score
        activePlayer === 0 ? activePlayer = 1 : activePlayer = 0;
        roundScore = 0;

        // Set current score of active player to 0 on switch
        document.getElementById('current-0').textContent = 0;
        document.getElementById('current-1').textContent = 0;

        // Add the active class to show which player is rolling dice
        document.querySelector('.player-0-panel').classList.toggle('active');
        document.querySelector('.player-1-panel').classList.toggle('active');

        // Reset dice on screen upon player switch
        document.querySelector('.dice').style.display = 'none';
    }

})





// use querySelector to get css props from html file using className
// use textContent to set html text content to num generated by dice
// document.querySelector('#current-' + activePlayer).textContent = dice;
// u can store elements from html in variables
// var x = document.querySelector('#score-' + activePlayer).textContent;
// console.log(x);